import React, {useEffect, useRef, useState} from 'react';
import {ActivityIndicator, Alert, Image, ImageBackground, KeyboardAvoidingView, Linking, Modal, PanResponder, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions} from 'react-native';
import {SafeAreaProvider, SafeAreaView} from 'react-native-safe-area-context';
import {StatusBar} from 'expo-status-bar';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {WebView} from 'react-native-webview';
import {SITE_URL, STORAGE_KEY, CROPS, id, seed, parseSaved, putShape, deleteShape, putLoad, binTotals} from './model';

const num=(n)=>Number(n).toLocaleString(undefined,{maximumFractionDigits:1});
function Button({title,onPress,primary=false,disabled=false}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.button,primary&&styles.primary,disabled&&{opacity:.45}]}><Text style={[styles.buttonText,primary&&{color:'#12210d'}]}>{title}</Text></Pressable>}
function Field({label,value,onChange,numeric=false}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} value={String(value??'')} onChangeText={onChange} keyboardType={numeric?'decimal-pad':'default'} autoCapitalize="none" placeholderTextColor="#78848a"/></View>}
function Choices({values,value,onChange}){return <View style={styles.wrap}>{values.map(v=><Pressable accessibilityRole="button" accessibilityState={{selected:v===value}} onPress={()=>onChange(v)} key={v} style={[styles.chip,value===v&&styles.chipActive]}><Text style={styles.text}>{v}</Text></Pressable>)}</View>}
function Shape({shape,width,height,editable,onSelect,onMove}){
  const [delta,setDelta]=useState({x:0,y:0});const latest=useRef({shape,width,height,onMove,onSelect});latest.current={shape,width,height,onMove,onSelect};
  const responder=useRef(PanResponder.create({onStartShouldSetPanResponder:()=>false,onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)+Math.abs(g.dy)>5,onPanResponderMove:(_,g)=>setDelta({x:g.dx,y:g.dy}),onPanResponderRelease:(_,g)=>{const v=latest.current;setDelta({x:0,y:0});v.onMove({...v.shape,x:Math.max(0,Math.min(100,v.shape.x+g.dx/(v.width*.76)*100)),y:Math.max(0,Math.min(100,v.shape.y+g.dy/(v.height*.76)*100))})},onPanResponderTerminate:()=>setDelta({x:0,y:0})})).current;
  const w=shape.width/100*width,h=shape.type==='circle'?w:shape.height/100*width;const cx=width*(.12+.76*shape.x/100),cy=height*(.12+.76*shape.y/100);
  return <View {...(editable?responder.panHandlers:{})} style={{position:'absolute',left:cx-w/2+delta.x,top:cy-h/2+delta.y,width:w,height:h}}><Pressable accessibilityRole="button" accessibilityLabel={(editable?'Configure ':'View ')+(shape.kind==='bin'?'bin '+shape.number:shape.label||shape.type)} onPress={()=>onSelect(shape)} disabled={!editable&&shape.kind!=='bin'} hitSlop={16} style={{width:w,height:h,alignItems:'center',justifyContent:'center'}}><View style={{position:'absolute',width:w,height:h,borderRadius:shape.type==='circle'?w/2:4,borderWidth:2,borderColor:shape.color,backgroundColor:shape.color+'22',transform:[{rotate:shape.rotation+'deg'}]}}/><Text numberOfLines={2} style={{color:'#f5f6f4',fontSize:Math.max(12,Math.min(18,w/4)),fontWeight:'700',textAlign:'center'}}>{shape.kind==='bin'?shape.number:shape.label}</Text></Pressable></View>
}
function Diagram({state,editable=false,onSelect,onMove}){
  const {width}=useWindowDimensions();const [zoom,setZoom]=useState(1);const stageWidth=Math.max(280,width-68)*zoom,stageHeight=stageWidth*.7;
  return <View><View style={styles.wrap}><Button title="View in +" onPress={()=>setZoom(z=>Math.min(3,z*1.25))}/><Button title="View out −" onPress={()=>setZoom(z=>Math.max(.6,z*.8))}/><Button title="Fit" onPress={()=>setZoom(1)}/><Text style={styles.muted}>{Math.round(zoom*100)}%</Text></View><ScrollView horizontal style={styles.diagram} nestedScrollEnabled><View style={{width:Math.max(width-68,stageWidth),height:Math.max(220,stageHeight)}}>{state.shapes.map(s=><Shape key={s.id} shape={s} width={stageWidth} height={stageHeight} editable={editable} onSelect={onSelect} onMove={onMove}/>)}</View></ScrollView></View>
}
function Connected(){
  const web=useRef(null);const [url,setUrl]=useState(SITE_URL);const [error,setError]=useState('');
  const openSafari=()=>Linking.openURL(SITE_URL).catch(()=>Alert.alert('Unable to open Safari','Open the Bushel site in your browser.'));
  return <View style={{flex:1}}><View style={styles.liveBar}><Text style={styles.muted}>Live site · your saved farm data</Text><View style={styles.wrap}><Button title="Reload" onPress={()=>{setError('');web.current?.reload()}}/><Button title="Open Safari" onPress={openSafari}/></View></View>{error?<View style={styles.panel}><Text style={styles.text}>{error}</Text><Button title="Try again" primary onPress={()=>{setError('');setUrl(SITE_URL)}}/></View>:<WebView ref={web} source={{uri:url}} style={{flex:1,backgroundColor:'#111517'}} sharedCookiesEnabled thirdPartyCookiesEnabled javaScriptEnabled domStorageEnabled startInLoadingState renderLoading={()=><ActivityIndicator style={styles.loading} color="#a6df83"/>} onError={()=>setError('The live site could not load. Check your connection, or use Open Safari.')} onHttpError={event=>{if(event.nativeEvent.statusCode>=500)setError('Bushel is temporarily unavailable. Try again.')}} onOpenWindow={event=>{const target=event.nativeEvent.targetUrl;if(target.startsWith('https://'))setUrl(target)}} onShouldStartLoadWithRequest={request=>{if(request.url.startsWith('https://')||request.url==='about:blank')return true;Linking.openURL(request.url).catch(()=>{});return false}}/>}<Text style={styles.liveNote}>Sign in to Bushel when prompted. If sign-in is blocked here, use Open Safari. Safari and this view may have separate sign-in sessions.</Text></View>
}
function Preview(){
  const [state,setState]=useState(null),[page,setPage]=useState('Home'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[load,setLoad]=useState({weight:'',crop:'Corn',binId:''}),[draft,setDraft]=useState(null),[selected,setSelected]=useState(null);const current=useRef(null),writing=useRef(false);
  useEffect(()=>{AsyncStorage.getItem(STORAGE_KEY).then(raw=>{const data=parseSaved(raw);current.current=data;setState(data)}).catch(()=>setError('Saved test data could not be loaded. Close and reopen the app. It has not been overwritten.'))},[]);
  async function save(change){if(writing.current)return false;writing.current=true;setBusy(true);try{const next=change(current.current);await AsyncStorage.setItem(STORAGE_KEY,JSON.stringify(next));current.current=next;setState(next);return true}catch(e){Alert.alert('Could not save',e.message||'Try again.');return false}finally{writing.current=false;setBusy(false)}}
  if(!state)return <View style={styles.panel}><Text style={styles.text}>{error||'Loading test preview…'}</Text>{!error&&<ActivityIndicator color="#a6df83"/>}</View>;
  const bins=state.shapes.filter(s=>s.kind==='bin'),total=state.loads.reduce((n,l)=>n+l.weight/CROPS[l.crop],0),selectedBin=state.shapes.find(s=>s.id===selected),details=selectedBin?binTotals(state,selectedBin.id):null;
  const newShape=(kind,type)=>setDraft({id:id(),kind,type,number:'',capacity:'0',label:'',width:'14',height:type==='circle'?'14':'10',rotation:'0',color:kind==='bin'?'#61c4ef':'#e9c78b',x:'50',y:'50'});
  const set=(key,value)=>setDraft(d=>({...d,[key]:value}));
  const shapeSave=async()=>{const shape={...draft};for(const key of ['capacity','width','height','rotation','x','y'])shape[key]=Number(shape[key]);if(await save(s=>putShape(s,shape)))setDraft(null)};
  const loadSave=async()=>{const saved={id:load.id||id(),createdAt:load.createdAt||Date.now(),crop:load.crop,binId:load.binId,weight:Number(load.weight)};if(await save(s=>putLoad(s,saved))){setLoad({weight:'',crop:load.crop,binId:load.binId});Alert.alert('Test load saved',num(saved.weight/CROPS[saved.crop])+' bu estimated.')}};
  const move=async shape=>{await save(s=>putShape(s,shape))};
  const goCart=()=>{setPage('Grain Cart');setDraft(null)};
  return <View style={{flex:1}}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.heading}>{page==='Home'?'Farm overview':page}</Text><Text style={styles.muted}>Test preview · stored on this phone · separate from live loads</Text>
    {page==='Home'&&<><ImageBackground source={require('./assets/harvest.jpg')} style={styles.photo} imageStyle={{borderRadius:20}}><View style={styles.photoShade}><Text style={styles.cardTitle}>Grain Cart</Text><Text style={styles.cardStat}>{num(state.loads[0]?.weight||0)} lb</Text><Button title="Add Weight" primary onPress={goCart}/></View></ImageBackground><Pressable onPress={()=>setPage('Grain Bins')}><ImageBackground source={require('./assets/bins.jpg')} style={styles.photo} imageStyle={{borderRadius:20}}><View style={styles.photoShade}><Text style={styles.cardTitle}>Grain Bins</Text><Text style={styles.cardStat}>{bins.length} bins · {num(total)} bu</Text><Text style={styles.text}>Open farm diagram</Text></View></ImageBackground></Pressable><View style={styles.panel}><Text style={styles.title}>Quick Stats</Text><Text style={styles.text}>{state.loads.length} test loads · {num(total)} estimated bushels</Text></View></>}
    {page==='Grain Cart'&&<><View style={styles.panel}><Text style={styles.title}>{load.id?'Edit saved load':'Grain Cart Weight'}</Text><Text style={styles.label}>Crop</Text><Choices values={Object.keys(CROPS)} value={load.crop} onChange={crop=>setLoad(l=>({...l,crop}))}/><Text style={styles.label}>Destination bin</Text><View style={styles.wrap}>{bins.map(b=><Button key={b.id} title={'Bin '+b.number} primary={load.binId===b.id} onPress={()=>setLoad(l=>({...l,binId:b.id}))}/>)}</View>{!bins.length&&<Button title="Set up bins in Settings" onPress={()=>setPage('Settings')}/>}<Field label="Current weight (lb)" value={load.weight} numeric onChange={weight=>setLoad(l=>({...l,weight}))}/><Text style={styles.muted}>{num(Number(load.weight||0)/CROPS[load.crop])} bu estimated · {CROPS[load.crop]} lb/bu</Text><Button title={load.id?'Save Changes':'Save Weight'} primary disabled={busy} onPress={loadSave}/>{load.id&&<Button title="Cancel edit" onPress={()=>setLoad({weight:'',crop:'Corn',binId:''})}/>}</View><View style={styles.panel}><Text style={styles.title}>Saved Load History</Text>{!state.loads.length&&<Text style={styles.muted}>No test loads yet.</Text>}{state.loads.map(l=><View key={l.id} style={styles.history}><Text style={styles.text}>{l.crop} · {num(l.weight)} lb · {num(l.weight/CROPS[l.crop])} bu</Text><Text style={styles.muted}>Bin {bins.find(b=>b.id===l.binId)?.number} · {new Date(l.createdAt).toLocaleString()}</Text><Button title="Edit" onPress={()=>setLoad({...l,weight:String(l.weight)})}/></View>)}</View></>}
    {page==='Grain Bins'&&<><View style={styles.panel}><Text style={styles.title}>Farm diagram</Text><Text style={styles.muted}>Tap a bin to see its grain and capacity.</Text><Diagram state={state} onSelect={s=>setSelected(s.id)}/></View><View style={styles.panel}><Text style={styles.title}>Stored grain</Text>{bins.filter(b=>binTotals(state,b.id).count).map(b=>{const t=binTotals(state,b.id);return <Pressable key={b.id} style={styles.history} onPress={()=>setSelected(b.id)}><Text style={styles.title}>Bin {b.number}</Text><Text style={styles.text}>{num(t.bushels)} bu · {num(t.weight)} lb</Text><Text style={styles.muted}>{Object.keys(t.products).join(', ')}</Text></Pressable>})}{!state.loads.length&&<Text style={styles.muted}>Save a test load and choose its destination bin.</Text>}</View></>}
    {page==='Settings'&&<View style={styles.panel}><Text style={styles.title}>Farm diagram setup</Text><Text style={styles.muted}>Drag saved items to position them. Tap an item to configure it.</Text><View style={styles.wrap}><Button title="+ Add bin" primary onPress={()=>newShape('bin','circle')}/><Button title="+ Circle" onPress={()=>newShape('decoration','circle')}/><Button title="+ Rectangle" onPress={()=>newShape('decoration','rectangle')}/></View><Diagram state={state} editable onSelect={s=>setDraft({...s})} onMove={move}/>{draft&&<View>{draft.kind==='bin'?<><Field label="Bin number" value={draft.number} onChange={v=>set('number',v)}/><Field label="Capacity (bu)" value={draft.capacity} numeric onChange={v=>set('capacity',v)}/></>:<Field label="Label" value={draft.label} onChange={v=>set('label',v)}/>}<Choices values={['circle','rectangle']} value={draft.type} onChange={v=>set('type',v)}/>{['width',...(draft.type==='rectangle'?['height']:[]),'rotation','x','y'].map(k=><Field key={k} label={{width:'Width / diameter (3–40)',height:'Height (3–40)',rotation:'Rotation (0–360°)',x:'Horizontal position (0–100%)',y:'Vertical position (0–100%)'}[k]} value={draft[k]} numeric onChange={v=>set(k,v)}/>)}<Text style={styles.label}>Colour</Text><Choices values={['#61c4ef','#a6df83','#e9c78b','#ed8f81']} value={draft.color} onChange={v=>set('color',v)}/><Field label="Custom colour (#RRGGBB)" value={draft.color} onChange={v=>set('color',v)}/><Button title="Save item" primary disabled={busy} onPress={shapeSave}/><Button title="Cancel" onPress={()=>setDraft(null)}/>{state.shapes.some(s=>s.id===draft.id)&&<Button title="Delete item" disabled={busy} onPress={()=>Alert.alert('Delete diagram item?','Bins with saved loads must be reassigned first.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{if(await save(s=>deleteShape(s,draft.id)))setDraft(null)}}])}/>}</View>}<Text style={styles.muted}>Preview changes stay on this phone and never change your live farm.</Text></View>}
  </ScrollView></KeyboardAvoidingView><View style={styles.tabs}>{['Home','Grain Cart','Grain Bins','Settings'].map(p=><Pressable key={p} onPress={()=>setPage(p)} style={styles.tab}><Text style={[styles.tabText,page===p&&{color:'#a6df83'}]}>{p}</Text></Pressable>)}</View><Modal visible={Boolean(selectedBin)} transparent animationType="slide" onRequestClose={()=>setSelected(null)}><View style={styles.modalShade}><View style={styles.modal}><ScrollView>{selectedBin&&<><Text style={styles.heading}>Bin {selectedBin.number}</Text><Text style={styles.cardStat}>{num(details.bushels)} bu</Text><Text style={styles.text}>{num(details.weight)} lb · {details.count} saved loads</Text><Text style={styles.text}>Capacity: {selectedBin.capacity?num(selectedBin.capacity)+' bu':'Not set'}</Text><Text style={styles.text}>Fill level: {selectedBin.capacity?Math.round(details.bushels/selectedBin.capacity*100)+'%':'—'}</Text>{Object.entries(details.products).map(([crop,t])=><Text key={crop} style={styles.text}>{crop}: {num(t.bushels)} bu · {num(t.weight)} lb</Text>)}<Text style={styles.muted}>Inventory from test loads. Moisture and temperature sensors are not connected.</Text></>}</ScrollView><Button title="Close" primary onPress={()=>setSelected(null)}/></View></View></Modal></View>
}
export default function App(){const [mode,setMode]=useState('Preview');return <SafeAreaProvider><SafeAreaView style={styles.root}><StatusBar style="light"/><View style={styles.header}><Image source={require('./assets/logo.png')} style={{width:42,height:42}}/><Text style={styles.brand}>BUSHEL</Text></View><View style={styles.mode}><Choices values={['Preview','Connected']} value={mode} onChange={setMode}/></View>{mode==='Preview'?<Preview/>:<Connected/>}</SafeAreaView></SafeAreaProvider>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#101517'},header:{flexDirection:'row',alignItems:'center',gap:12,padding:16,paddingBottom:8},brand:{color:'#f5f3ec',fontSize:27,fontWeight:'800',letterSpacing:2},mode:{paddingHorizontal:16,paddingBottom:6},content:{padding:18,paddingBottom:30,gap:14},heading:{color:'#f5f6f4',fontSize:27,fontWeight:'700'},title:{color:'#f5f6f4',fontSize:21,fontWeight:'650',marginBottom:8},text:{color:'#f5f6f4',fontSize:16,lineHeight:25},muted:{color:'#b8bec2',fontSize:14,lineHeight:22},label:{color:'#c6cfcb',fontSize:15,marginBottom:8},panel:{backgroundColor:'#1b2225',padding:18,borderRadius:20,borderWidth:1,borderColor:'#30383b',gap:12},photo:{height:230,overflow:'hidden',borderRadius:20},photoShade:{flex:1,backgroundColor:'#0006',padding:22,justifyContent:'space-between'},cardTitle:{fontSize:27,fontWeight:'700',color:'#fff'},cardStat:{fontSize:27,fontWeight:'700',color:'#a6df83',marginVertical:10},button:{minHeight:44,paddingHorizontal:14,paddingVertical:12,borderRadius:12,backgroundColor:'#263035',borderWidth:1,borderColor:'#40504d',justifyContent:'center',alignItems:'center'},primary:{backgroundColor:'#a6df83',borderColor:'#a6df83'},buttonText:{color:'#f5f6f4',fontSize:15,fontWeight:'650'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8,alignItems:'center',marginVertical:4},chip:{paddingVertical:11,paddingHorizontal:15,borderRadius:12,borderWidth:1,borderColor:'#3b464b'},chipActive:{backgroundColor:'#36502e',borderColor:'#a6df83'},field:{marginVertical:4},input:{minHeight:48,color:'#fff',fontSize:17,padding:13,borderWidth:1,borderColor:'#52625a',borderRadius:12,backgroundColor:'#111719'},diagram:{borderWidth:1,borderColor:'#3a4b45',backgroundColor:'#15221c',borderRadius:14,marginTop:12},history:{paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#384247',gap:8},tabs:{flexDirection:'row',backgroundColor:'#161d20',borderTopWidth:1,borderTopColor:'#30383b'},tab:{flex:1,minHeight:56,alignItems:'center',justifyContent:'center',padding:7},tabText:{color:'#b8bec2',fontSize:12,fontWeight:'600',textAlign:'center'},modalShade:{flex:1,backgroundColor:'#0009',justifyContent:'center',padding:22},modal:{maxHeight:'85%',backgroundColor:'#1b2225',padding:24,borderRadius:22,gap:16},liveBar:{paddingHorizontal:16,paddingBottom:10},liveNote:{color:'#b8bec2',fontSize:12,lineHeight:18,padding:12},loading:{position:'absolute',alignSelf:'center',top:'40%'},});
